### ISSUE TITLE
"No release history for views-7.37"

### ISSUE THREAD

**Issue by axel-rutz** [jpstacey/drush-m2c#4]
Broken json and message like "No release history for views-7.37"

Workaround:
In the original makefile, replace
core=7.37
with
core=7.x

**Comment by jpstacey** [comment]
Thanks for your feedback on these issues.

With this one, the original makefile is broken. you should never write "core=7.37" in your makefile, so this isn't a bug with this software. See e.g. https://groups.drupal.org/node/262923 .

If you want to specify a Drupal version, you write:

```
core = "7.x"
projects[drupal][version] = "7.37"
```
