### ISSUE TITLE
Call to undefined function release_info_fetch()

### ISSUE THREAD

**Issue by axel-rutz** [jpstacey/drush-m2c#5]
PHP Fatal error:  Call to undefined function release_info_fetch() in /home/xl/.drush/drush-m2c/hacks/make.inc on line 106

Workaround: Use drush 6

**Comment by jpstacey** [comment]
Thanks: I've edited the README.md to mention that Drush 6.x is required.

Again, thank you for your work feeding back on your recent tickets. As I say, I'm not planning any further maintenance on this project myself, but you are welcome to submit pull requests and I will try to set aside the time to review them!
