### ISSUE TITLE
Senseless version strings in json

### ISSUE THREAD

**Issue by axel-rutz** [jpstacey/drush-m2c#6]
We should convert
2.x => 7.2.x
and have default version 7.x

(assuming that no one needs this for 8.x ;-)

**Comment by jpstacey** [comment]
Thanks for the feedback. As this is only alpha software, I'm not doing any ongoing maintenance of issues. However, I'd be happy to look at pull requests to fix bugs.

As far as I'm aware this works as it stands but if you can provide a makefile that triggers a bug then feel free to open a new ticket.
