### ISSUE TITLE
Do not output repositories

### ISSUE THREAD

**Issue by geek-merlin** [jpstacey/drush-m2c#7]
Now that we have https://packagist.drupal-composer.org/,
we don't need to output drupal module repositories info anymore

**Comment by jpstacey** [comment]
Thanks for the feedback. When this code was written, the Packagist repository was not to be relied upon. So I think this is a feature request rather than a bug.

As this is only an alpha release I can look at PRs but I don't plan to do any further maintenance on this codebase.

**Comment by geek-merlin** [comment]
I know this is a dead horse ;-), just using this as a public notepad for some dirty ad-hoc patches in my fork.
